### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [PCSTrac/napi#2]
If you really like Prepared Statements more than regular queries, here's how you can properly extend the protocol, via the Initialization Options, and event [extend](https://github.com/vitaly-t/pg-promise#extend):

```js
var options = {
    extend: function (obj) {
        obj.psNone = function (query, params) {
            return obj.none(dbh.buildPrepared(query, params));
        };
        obj.psOne = function (query, params) {
            return obj.one(dbh.buildPrepared(query, params));
        };
        obj.psQuery = function (query, params, qrm) { // generic query, with QueryResultMask
            return obj.query(dbh.buildPrepared(query, params), qrm);
        };
    }
};
```
so that instead of writing this:
```js
db.none(dbh.buildPrepared(
    'DELETE FROM account_location WHERE account_id = $1',
    [id]
));
```
you can write this:
```js
db.psNone('DELETE FROM account_location WHERE account_id = $1', [id]);
```

**Comment by Klathmon** [comment]
Well that's a much more clean way of doing it!

i was actually thinking about wrapping the one/none/query/etc... functions in the dbh thing but working with extend will actually be nicer and based on the linked docs i'm assuming i could just dump random functions in there so i could drop the dbh file entirely and that's one less dependency i need to manage.

Thanks!

**Comment by vitaly-t** [comment]
>i was actually thinking about wrapping the one/none/query/etc... functions in the dbh thing

It wouldn't work, because you need that thing to work automatically through the context provided inside tasks and transactions, and you cannot extend that context in any way, other than through event `extend`. That's one of the main points why it is there.

**Comment by vitaly-t** [comment]
Regarding multi-line queries like you got here: https://github.com/Klathmon/PCS-API/blob/master/app/login/v1/models/account.js
And in other places, see [Query Files](https://github.com/vitaly-t/pg-promise#query-files) ;)

**Comment by Klathmon** [comment]
@vitaly-t 

Hey, thanks for the crazy amount of help you've given for this. 

Do you have a place where you are accepting donations or something for your work on pg-promise?

**Comment by vitaly-t** [comment]
I wish I had a fund set up :)

**Comment by Klathmon** [comment]
well if you do set one up, ping me.

**Comment by vitaly-t** [comment]
OK :) 

I have set up branch 4.0 for the library, with lots of check-ins, which includes:

* New error types, including: QueryError, ConnectionError, QueryFileError
* PreparedStatements will no longer throw any errors, it will do late error reporting, during query execution (as a rejection reason);
* PreparedStatements will automatically support QueryFile for property `text`.

In all fairness, I already got the last 2 working. But it will take a lots of documentation + test updates to bring this to a point ready to be released. Someday though :)

**Comment by vitaly-t** [comment]
@Klathmon [Version 4.0.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.0.0) is out :)

One of the features is what you asked for - using `QueryFile` for `text` field in Prepared Statements ;)

**Comment by vitaly-t** [comment]
@Klathmon Since you are using multi-inserts, see the new feature being developed, and is already working - [formatting helpers](http://vitaly-t.github.io/pg-promise/helpers.html). It supports proper generation of:

* single inserts
* multi-inserts
* single updates
* multi-updates
