### ISSUE TITLE
incorrect db context used

### ISSUE THREAD

**Issue by vitaly-t** [PCSTrac/napi#4]
from here: https://github.com/PCSTrac/napi/blob/master/test/v1/unit.js

code:
```js
return db.tx((tx) => {
        return db.none(pgPromise.QueryFile('./sql/ADD_TEST_DATA.sql', {minify: true}))
      })
```
should be:
```js
return db.tx((tx) => {
        return tx.none(pgPromise.QueryFile('./sql/ADD_TEST_DATA.sql', {minify: true}))
      })
```
Otherwise it is breaking the transaction flow, i.e. you are executing the transaction on one connection, and the query on a different one.

**Comment by Klathmon** [comment]
Thanks, quick question while you are here.

I'm working on trying to use the query files, but it looks like the partial application of the params isn't quite what i thought it was...

I'm trying to replace the query at https://github.com/PCSTrac/napi/blob/master/app/v1/models/account.js#L225 first as a test. I'm kind of rolling my own "query builder" here as i replace the where and limit parts of the query with different strings depending on what i need.

I notice when i use query files and the `param` object, it's formatting the queries like the below:

```
SELECT
  account.id,
  account.name,
  account.password,
  account.email,
  account.created,
FROM account
LEFT JOIN location AS company_location ON company_location.company_id = company.id
'WHERE account.id = $1'
GROUP BY account.id, company.*, role.*
'LIMIT 1'
```

Where the `'WHERE account.id = $1'` shouldn't have quotes around it and i think it's causing issues in it being parsed correctly.

Is there an easy way to do what i'm trying to do here?

**Comment by vitaly-t** [comment]
Amend the variable that resolves into `WHERE account.id = $1` with `^` to inject the raw value ;)

**Comment by Klathmon** [comment]
Thanks, you rock! I was just looking at the docs as i remembered something about raw input...

**Comment by Klathmon** [comment]
One last question if you don't mind:

[here](http://vitaly-t.github.io/pg-promise/QueryFile.html) you say "For any given SQL file you should only create a single instance of this class throughout the application."

In that case I should "cache" the objects created by by QueryFile myself and reuse them wherever possible instead of re-running the `new QueryFile(...` every time i want to query?

**Comment by vitaly-t** [comment]
Absolutely. See how it is done in [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo), and see [the API example](http://vitaly-t.github.io/pg-promise/QueryFile.html).

Not only re-creating the object (instead of caching) creates unnecessary object instance, but you would also lose such useful feature as its `debug` mode, which allows you to write SQL scripts and see immediate updates without restarting the app.

**Comment by Klathmon** [comment]
Can Query Files be used with Prepared Statements? I'm getting a `TypeError: 'text' must be a non-empty text string.` when i try to do it, but the same query works fine if I skip the prepared statement and pass it directly to the query method along with the values...

**Comment by vitaly-t** [comment]
Nope. The reason I didn't add QueryFile support into the Prepared Statements is because the latter implies server-side parameter formatting all the way. Not sure if that's good enough a reason, but there it is.

But it sounds like something to consider adding :)

**Comment by vitaly-t** [comment]
Actually, another reason is that QueryFile supports late error reporting, via query methods, while Prepared Statements are expected to error during construction... it's a tricky one :)

**Comment by Klathmon** [comment]
Makes sense. 

Any issues you see with using query.toString() to "fake" it for now?

I'd really prefer prepared statements as some of these queries are doozies and the prep makes a pretty big difference for some of them.

Don't go out of your way to add my use case, i know it's a pretty abnormal one :smile:

**Comment by vitaly-t** [comment]
I'm beginning to doubt my decision when I made the new [PreparedStatement](http://vitaly-t.github.io/pg-promise/PreparedStatement.html) type throw error during initialization. Maybe it should use late error reporting, the same as QueryFile, then I could merry them all :)
