### ISSUE TITLE
better caching?

### ISSUE THREAD

**Issue by vitaly-t** [PCSTrac/napi#5]
Noticed your caching logic there: https://github.com/PCSTrac/napi/blob/51224ff3942bddd92c6501e7871857c77b626cab/app/v1/helpers/dbHelpers.js

It may be a better solution to cache `PreparedStatement` instead, based on the unique `name`.

Then you can reuse all such objects. You would just set `ps.values = ...` just before using it ;)

That's just a general pattern, not sure if it is applicable in your case.

Just to let you know ;)

**Comment by vitaly-t** [comment]
Also, it is a good idea to use `minify` in development mode too, to let it parse and minify the SQL ;)
i.e. I would change `minify: !devMode,` to `minify: devMode,` ;)

**Comment by Klathmon** [comment]
Oh that's a good catch. before i was using query.query (bad idea, but it worked!) and i just replaced that with query.

As for using minify in dev mode, i want to keep it off in dev just so i can see errors easier when they are dumped to console.

**Comment by vitaly-t** [comment]
>before i was using query.query (bad idea, but it worked!)

It only worked for as long as there weren't errors reported. Because inside the query the logic of using it is:

```js
if(ps.error){
// reject with the error
}else{
 // use ps.query
}
```

**Comment by Klathmon** [comment]
Cool.

So i just pulled query caching out to it's own file. 

https://github.com/PCSTrac/napi/blob/master/app/v1/helpers/queryCacher.js

**Comment by vitaly-t** [comment]
Nice! :)

Just to keep in mind that between the request for a prepared statement from the cache and passing it into a query method there cannot be any async call in the middle, or else the prepared statement object will mutate (if something updates its `values` in parallel).

Basically it means, the cache is to be used only immediately before calling a query method.
